name: radar

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: radar123
      POSTGRES_DB: radar
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
