name: radar

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: radar
      POSTGRES_PASSWORD: radar123
      POSTGRES_DB: radar
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  radar:
    build: .
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: radar
      DB_USER: radar
      DB_PASSWORD: radar123
      INIT_DB: true
      SEED_DB: true
    depends_on:
      - postgres

volumes:
  postgres-data:
