services:
  radar:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src/lib/server/content:/app/src/lib/server/content
    networks:
      - radar_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '3001:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - radar
    networks:
      - radar_network

networks:
  radar_network:
    driver: bridge

volumes:
  nginx_cache:
